### ISSUE TITLE
Could you make each level embed the speedrun.com link for the run?

### ISSUE THREAD

**Issue by NotDaemonius** [EzraIII/ezraiii.github.io#4]

**Comment by mitchell-merry** [comment]
You mean the level name text "A01" would be a link to the level?

**Comment by NotDaemonius** [comment]
A link to the run on speedrun.com

**Comment by mitchell-merry** [comment]
Those changes add a link to the board in each of the levels, but if you specifically want a link to the run, let me know. Keep in mind that it'll probably have to arbitrarily choose a single run if there is a tie.

If this is the case, would it be preferred to link to the src page or the video link directly?

**Comment by EzraIII** [comment]
There are now links to the level leaderboard for each level. There are also links to the actual runs attached to the time for every untied WR. The reason that I haven't included links to tied WR runs is that it's likely going to be unfair to one runner or the other. I will now close this issue. If anyone feel that this issue has not been fully resolved, they may feel free to open another issue with more details.
